### ISSUE TITLE
Unable to cross compile with Swift 5.10 due to typo in swift_build_scripts

### ISSUE THREAD

**Issue by xtremekforever** [swiftlang/swift#75341]
### Description

When I try to cross compile Swift 5.10 using the utils/build-script, I get the following crash:

```bash
Traceback (most recent call last):
  File "/home/builduser/workspace/swift/./utils/build-script", line 800, in <module>
    exit_code = main()
  File "/home/builduser/tmp/swift-armv7/workspace/swift/./utils/build-script", line 795, in main
    return main_normal()
  File "/home/builduser/tmp/swift-armv7/workspace/swift/./utils/build-script", line 740, in main_normal
    invocation.execute()
  File "/home/builduser/tmp/swift-armv7/workspace/swift/utils/swift_build_support/swift_build_support/build_script_invocation.py", line 734, in execute
    self._execute(pipeline, all_host_names)
  File "/home/builduser/tmp/swift-armv7/workspace/swift/utils/swift_build_support/swift_build_support/build_script_invocation.py", line 794, in _execute
    self.execute_product_build_steps(product_class, host_target)
  File "/home/builduser/tmp/swift-armv7/workspace/swift/utils/swift_build_support/swift_build_support/build_script_invocation.py", line 855, in execute_product_build_steps
    product.build(host_target)
  File "/home/builduser/tmp/swift-armv7/workspace/swift/utils/swift_build_support/swift_build_support/products/llvm.py", line 212, in build
    toolchain_file = self.generate_linux_toolchain_file(platform, arch)
  File "/home/builduser/tmp/swift-armv7/workspace/swift/utils/swift_build_support/swift_build_support/products/product.py", line 403, in generate_linux_toolchain_file
    maybe_sysroot = self.get_linux_sysroot(platform, arch)
  File "/home/builduser/tmp/swift-armv7/workspace/swift/utils/swift_build_support/swift_build_support/products/product.py", line 373, in get_linux_sysroot
    sysroot_arch, abi = self.get_linux_target_components(arch)
ValueError: too many values to unpack (expected 2)
```

I did a little bit of investigation, and turns out it's just a simple typo in this method in `utils/swift_build_support/swift_build_support/products/product.py`:

```python
    def get_linux_sysroot(self, platform, arch):
        if not self.is_cross_compile_target('{}-{}'.format(platform, arch)):
            return None
        sysroot_arch, abi = self.get_linux_target_components(arch)
        # $ARCH-$PLATFORM-$ABI
        # E.x.: aarch64-linux-gnu
        sysroot_dirname = '{}-{}-{}'.format(sysroot_arch, platform, abi)
        return os.path.join(os.sep, 'usr', sysroot_dirname)
```

The `get_linux_target_components()` method returns 3 values instead of 2, so the `sysroot_arch, abi = self.get_linux_target_components(arch)` line should be: `sysroot_arch, _, abi = self.get_linux_target_components(arch)`.

### Reproduction

One easy way to reproduce this is by checking out the release/5.10 branch of swiftlang/swift, then running the build-script:

`./swift/utils/build-script --cross-compile-hosts=linux-armv7 --skip-build-llvm`

After it gets past the LLVM build stuff, the build crashes with the error above.

### Expected behavior

I expect to not get a crash when cross compiling. This seems like just a small typo, and something introduced starting with Swift 5.10 (it was not present in 5.9).

### Environment

Swift version 5.10.1 (swift-5.10.1-RELEASE)
Target: x86_64-unknown-linux-gnu

**Comment by shahmishal** [comment]
cc: @edymtt @etcwilde

**Comment by xtremekforever** [comment]
This also happens in Swift 6.0 and later as well. I think a small patch that simply fixes the issue would be appropriate. @finagolfin is there a way to validate that the patch doesn't break the alpine build- is there a CI somewhere or instructions for building?

**Comment by finagolfin** [comment]
Are you sure that doesn't work? I'm not sure what you're trying to do exactly. Please paste the full command that's failing for you. The simple sample command you gave has never worked, and would fail in other ways anyway.

**Comment by xtremekforever** [comment]
Let me try this again with a recent trunk of Swift. Maybe things have changed!

**Comment by xtremekforever** [comment]
This is still happening in the latest development snapshot. I am doing the following:

```bash
$ git clone https://github.com/swiftlang/swift.git
$ ./swift/utils/update-checkout --clone --tag swift-DEVELOPMENT-SNAPSHOT-2025-01-10-a --skip-repository cmark --skip-repository cmake
$ ./swift/utils/build-script --cross-compile-hosts=linux-armv7 --build-llvm=0 --skip-build-cmark --skip-build-llvm \
     --skip-early-swift-driver --skip-early-swiftsyntax
```

And after it gets past configuring LLVM, I get the error from python:

```
Traceback (most recent call last):
  File "/home/xtremek/Programming/swiftlang/swift-main-armv7-build/./swift/utils/build-script", line 829, in <module>
    exit_code = main()
                ^^^^^^
  File "/home/xtremek/Programming/swiftlang/swift-main-armv7-build/./swift/utils/build-script", line 824, in main
    return main_normal()
           ^^^^^^^^^^^^^
  File "/home/xtremek/Programming/swiftlang/swift-main-armv7-build/./swift/utils/build-script", line 769, in main_normal
    invocation.execute()
  File "/home/xtremek/Programming/swiftlang/swift-main-armv7-build/swift/utils/swift_build_support/swift_build_support/build_script_invocation.py", line 795, in execute
    self._execute(pipeline, all_host_names)
  File "/home/xtremek/Programming/swiftlang/swift-main-armv7-build/swift/utils/swift_build_support/swift_build_support/build_script_invocation.py", line 855, in _execute
    self.execute_product_build_steps(product_class, host_target)
  File "/home/xtremek/Programming/swiftlang/swift-main-armv7-build/swift/utils/swift_build_support/swift_build_support/build_script_invocation.py", line 916, in execute_product_build_steps
    product.build(host_target)
  File "/home/xtremek/Programming/swiftlang/swift-main-armv7-build/swift/utils/swift_build_support/swift_build_support/products/llvm.py", line 236, in build
    toolchain_file = self.generate_linux_toolchain_file(platform, arch)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xtremek/Programming/swiftlang/swift-main-armv7-build/swift/utils/swift_build_support/swift_build_support/products/product.py", line 412, in generate_linux_toolchain_file
    maybe_sysroot = self.get_linux_sysroot(platform, arch)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xtremek/Programming/swiftlang/swift-main-armv7-build/swift/utils/swift_build_support/swift_build_support/products/product.py", line 382, in get_linux_sysroot
    sysroot_arch, abi = self.get_linux_target_components(arch)
    ^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
```

So, I think a typo fix is in order here, and we can confirm the CIs don't break with the tiny patch.

**Comment by finagolfin** [comment]
That build-script command isn't going to work either, as you completely disable building LLVM, but do not provide a prebuilt toolchain to use instead.

What are you trying to build here, just the stdlib or a fresh Swift compiler also? If just the stdlib with a prebuilt Swift toolchain, take a look at [the standalone stdlib preset](https://github.com/swiftlang/swift/blob/2f639fc2edefa70d901f7231ae8396c64dd6249a/utils/build-presets.ini#L2617) or [the Android doc](https://github.com/swiftlang/swift/blob/main/docs/Android.md#1-building-the-standalone-swift-stdlib-for-android) for the kind of flags that need to be passed in.

As for the linked pull you submitted, that is a minor Python issue that has nothing to do with this build command not working, as this is going to keep failing in other ways.

**Comment by xtremekforever** [comment]
> That build-script command isn't going to work either, as you completely disable building LLVM, but do not provide a prebuilt toolchain to use instead.
> 
> What are you trying to build here, just the stdlib or a fresh Swift compiler also? If just the stdlib with a prebuilt Swift toolchain, take a look at [the standalone stdlib preset](https://github.com/swiftlang/swift/blob/2f639fc2edefa70d901f7231ae8396c64dd6249a/utils/build-presets.ini#L2617) or [the Android doc](https://github.com/swiftlang/swift/blob/main/docs/Android.md#1-building-the-standalone-swift-stdlib-for-android) for the kind of flags that need to be passed in.
> 
> As for the linked pull you submitted, that is a minor Python issue that has nothing to do with this build command not working, as this is going to keep failing in other ways.

So many things don't work with cross-compiling to Linux using the build scripts that I'm not even trying to do that. I'm just trying to fix the first crash we see here, and make sure that the fix does not break anything else. So I'm tackling one at a time.

This one is just the first roadblock to actually starting to build llvm, earlyswiftdriver, and cmark. I just found that the command above could trigger the crash and also prove that the crash is gone. That's it!

With this fix I am now working on making llvm, earlyswiftdriver, and cmark to cross-compile correctly when you provide: `cross-compile-hosts=linux-<arch>` to the build scripts. That will be my next step. After that, it'll be the Swift stdlib to make sure that it uses the correct flags, linker, and uses the external sysroot as well. But for each step we need to make sure that the changes don't break something else!

**Comment by finagolfin** [comment]
OK, but you need to use `build-script` right in the first place, which gets us back to the question I originally asked: what do you intend to build with `./swift/utils/build-script --cross-compile-hosts=linux-armv7 --build-llvm=0 --skip-build-cmark --skip-build-llvm --skip-early-swift-driver --skip-early-swiftsyntax`? Because `build-script` is a power tool, so it will not tell you that you are holding it wrong, and that command makes no sense.

What do you want that command to build for you, a native Swift compiler for the linux host and a cross-compiled stdlib for linux armv7? Please enumerate what build products you expect that to produce, assuming no bugs, because I assure you that you are holding it wrong.

**Comment by xtremekforever** [comment]
> OK, but you need to use `build-script` right in the first place, which gets us back to the question I originally asked: what do you intend to build with `./swift/utils/build-script --cross-compile-hosts=linux-armv7 --build-llvm=0 --skip-build-cmark --skip-build-llvm --skip-early-swift-driver --skip-early-swiftsyntax`? Because `build-script` is a power tool, so it will not tell you that you are holding it wrong, and that command makes no sense.
> 
> What do you want that command to build for you, a native Swift compiler for the linux host and a cross-compiled stdlib for linux armv7? Please enumerate what build products you expect that to produce, assuming no bugs, because I assure you that you are holding it wrong.

I added some context to the ticket. I don't want to build the Swift compiler for armv7 yet, as I have no idea how to get to this point. The first goal is just getting the build-scripts to be able to successfully build the minimal stdlib + core libraries.
