### ISSUE TITLE
utils/update-checkout error from protocolbuffers/protobuf

### ISSUE THREAD

**Issue by vanvoorden** [swiftlang/swift#76913]
### Description

I'm seeing some error from the `utils/update-checkout` script. It seems to be related to the `protocolbuffers/protobuf` repo. My current local head checkout is 5fa12d31ae042db54e1b586da546741882d826e7.

### Reproduction

```text
utils/update-checkout --clone-with-ssh
...
[llbuild]                               warning: 4587181158d3449bbdb3de2bb6a6b644f3f75f8d:.gitmodules, multiple configurations found for 'submodule.thirdparty/swift-protobuf.path'. Skipping second one!
[llbuild]                               warning: 4587181158d3449bbdb3de2bb6a6b644f3f75f8d:.gitmodules, multiple configurations found for 'submodule.thirdparty/swift-protobuf.url'. Skipping second one!
[llbuild]                               warning: 4587181158d3449bbdb3de2bb6a6b644f3f75f8d:.gitmodules, multiple configurations found for 'submodule.thirdparty/swift-protobuf.path'. Skipping second one!
[llbuild]                               warning: 4587181158d3449bbdb3de2bb6a6b644f3f75f8d:.gitmodules, multiple configurations found for 'submodule.thirdparty/swift-protobuf.url'. Skipping second one!
[llbuild]                               Fetching submodule thirdparty/protobuf
[llbuild]                               From https://github.com/protocolbuffers/protobuf
[llbuild]                                  64febd99e..8f134aefa  27.x              -> origin/27.x
[llbuild]                                  c4124f9ec..fe3bb07da  28.x              -> origin/28.x
[llbuild]                                * [new branch]          29.x              -> origin/29.x
[llbuild]                                  b022c5491..6690ab42d  main              -> origin/main
[llbuild]                                * [new branch]          main-202409302244 -> origin/main-202409302244
[llbuild]                                * [new branch]          php-regen         -> origin/php-regen
[llbuild]                                * [new branch]          test_662106123    -> origin/test_662106123
[llbuild]                                * [new branch]          test_670256177    -> origin/test_670256177
[llbuild]                                * [new branch]          test_671457047    -> origin/test_671457047
[llbuild]                                + 2315412a9...5a5a3bebe test_675278793    -> origin/test_675278793  (forced update)
[llbuild]                                * [new branch]          test_679706926    -> origin/test_679706926
[llbuild]                                * [new branch]          test_680591096    -> origin/test_680591096
[llbuild]                                * [new branch]          test_680876523    -> origin/test_680876523
[llbuild]                                * [new branch]          test_681096219    -> origin/test_681096219
[llbuild]                                * [new branch]          test_681422683    -> origin/test_681422683
[llbuild]                                * [new branch]          test_681862395    -> origin/test_681862395
[llbuild]                                * [new branch]          test_682024767    -> origin/test_682024767
[llbuild]                                * [new branch]          test_682053101    -> origin/test_682053101
[llbuild]                                * [new branch]          test_682129820    -> origin/test_682129820
[llbuild]                                * [new branch]          test_682342945    -> origin/test_682342945
[llbuild]                                * [new branch]          test_682374092    -> origin/test_682374092
[llbuild]                                * [new branch]          test_682400223    -> origin/test_682400223
[llbuild]                                * [new branch]          test_682453101    -> origin/test_682453101
[llbuild]                                * [new branch]          test_682986476    -> origin/test_682986476
[llbuild]                                * [new branch]          test_683309141    -> origin/test_683309141
[llbuild]                                * [new branch]          test_683315391    -> origin/test_683315391
[llbuild]                                * [new branch]          test_683317316    -> origin/test_683317316
[llbuild]                                * [new branch]          test_683457486    -> origin/test_683457486
[llbuild]                                * [new branch]          test_683458654    -> origin/test_683458654
[llbuild]                                * [new branch]          test_683463261    -> origin/test_683463261
[llbuild]                                * [new branch]          test_683476020    -> origin/test_683476020
[llbuild]                                * [new branch]          test_683507452    -> origin/test_683507452
[llbuild]                                * [new branch]          test_683530545    -> origin/test_683530545
[llbuild]                                * [new branch]          test_683542926    -> origin/test_683542926
[llbuild]                                * [new branch]          test_683606041    -> origin/test_683606041
[llbuild]                                * [new branch]          test_683631028    -> origin/test_683631028
[llbuild]                                * [new branch]          test_683642009    -> origin/test_683642009
[llbuild]                                * [new branch]          test_683660512    -> origin/test_683660512
[llbuild]                                * [new tag]             v29-dev           -> v29-dev
[llbuild]                                * [new tag]             v29.0-rc1         -> v29.0-rc1
[llbuild]                                * [new tag]             v3.29.0-rc1       -> v3.29.0-rc1
[llbuild]                                * [new tag]             v5.29.0-rc1       -> v5.29.0-rc1
[libxml2]                               + git submodule update --recursive
[llbuild]                               + git rebase FETCH_HEAD
[llbuild]                               error: The following untracked working tree files would be overwritten by checkout:
[llbuild]                               	thirdparty/protobuf/.bazelignore
[llbuild]                               	thirdparty/protobuf/.bazelrc
[llbuild]                               	thirdparty/protobuf/.bcr/README.md
[llbuild]                               	thirdparty/protobuf/.bcr/metadata.template.json
[llbuild]                               	thirdparty/protobuf/.bcr/presubmit.yml
[llbuild]                               	thirdparty/protobuf/.bcr/source.template.json
[llbuild]                               	thirdparty/protobuf/.clang-format
[llbuild]                               	thirdparty/protobuf/.github/BUILD.bazel
[llbuild]                               	thirdparty/protobuf/.github/CODEOWNERS
[llbuild]                               	thirdparty/protobuf/.github/ISSUE_TEMPLATE/bug_report.md
[llbuild]                               	thirdparty/protobuf/.github/ISSUE_TEMPLATE/feature_request.md
[llbuild]                               	thirdparty/protobuf/.github/dependabot.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/README.md
[llbuild]                               	thirdparty/protobuf/.github/workflows/clear_caches.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/forked_pr_workflow_check.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/janitor.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/scorecard.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/staleness_check.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/staleness_refresh.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/test_bazel.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/test_cpp.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/test_csharp.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/test_java.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/test_objectivec.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/test_php.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/test_php_ext.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/test_python.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/test_ruby.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/test_runner.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/test_rust.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/test_upb.yml
[llbuild]                               	thirdparty/protobuf/.github/workflows/update_php_repo.yml
[llbuild]                               	thirdparty/protobuf/.gitignore
[llbuild]                               	thirdparty/protobuf/.gitmodules
[llbuild]                               	thirdparty/protobuf/.readthedocs.yml
[llbuild]                               	thirdparty/protobuf/BUILD.bazel
[llbuild]                               	thirdparty/protobuf/CMakeLists.txt
[llbuild]                               	thirdparty/protobuf/CODE_OF_CONDUCT.md
[llbuild]                               	thirdparty/protobuf/CONTRIBUTING.md
[llbuild]                               	thirdparty/protobuf/CONTRIBUTORS.txt
[llbuild]                               	thirdparty/protobuf/Cargo.bazel.lock
[llbuild]                               	thirdparty/protobuf/Cargo.lock
[llbuild]                               	thirdparty/protobuf/LICENSE
[llbuild]                               	thirdparty/protobuf/MODULE.bazel
[llbuild]                               	thirdparty/protobuf/PrivacyInfo.xcprivacy
[llbuild]                               	thirdparty/protobuf/Protobuf-C++.podspec
[llbuild]                               	thirdparty/protobuf/Protobuf.podspec
[llbuild]                               	thirdparty/protobuf/README.md
[llbuild]                               	thirdparty/protobuf/SECURITY.md
[llbuild]                               	thirdparty/protobuf/WORKSPACE
[llbuild]                               	thirdparty/protobuf/appveyor.bat
[llbuild]                               	thirdparty/protobuf/appveyor.yml
[llbuild]                               	thirdparty/protobuf/bazel/BUILD.bazel
[llbuild]                               	thirdparty/protobuf/bazel/cc_proto_library.bzl
[llbuild]                               	thirdparty/protobuf/bazel/common/BUILD.bazel
[llbuild]                               	thirdparty/protobuf/bazel/common/proto_common.bzl
[llbuild]                               	thirdparty/protobuf/bazel/common/proto_info.bzl
[llbuild]                               	thirdparty/protobuf/bazel/common/proto_lang_toolchain_info.bzl
[llbuild]                               	thirdparty/protobuf/bazel/java_lite_proto_library.bzl
[llbuild]                               	thirdparty/protobuf/bazel/java_proto_library.bzl
[llbuild]                               	thirdparty/protobuf/bazel/private/BUILD.bazel
[llbuild]                               	thirdparty/protobuf/bazel/private/native.bzl
[llbuild]                               	thirdparty/protobuf/bazel/private/proto_toolchain_rule.bzl
[llbuild]                               	thirdparty/protobuf/bazel/private/upb_proto_library_internal/aspect.bzl
[llbuild]                               	thirdparty/protobuf/bazel/private/upb_proto_library_internal/cc_library_func.bzl
[llbuild]                               	thirdparty/protobuf/bazel/private/upb_proto_library_internal/copts.bzl
[llbuild]                               	thirdparty/protobuf/bazel/private/upb_proto_library_internal/rule.bzl
[llbuild]                               	thirdparty/protobuf/bazel/proto_library.bzl
[llbuild]                               	thirdparty/protobuf/bazel/py_proto_library.bzl
[llbuild]                               	thirdparty/protobuf/bazel/system_python.bzl
[llbuild]                               	thirdparty/protobuf/bazel/toolchains/BUILD.bazel
[llbuild]                               	thirdparty/protobuf/bazel/toolchains/proto_lang_toolchain.bzl
[llbuild]                               	thirdparty/protobuf/bazel/toolchains/proto_toolchain.bzl
[llbuild]                               	thirdparty/protobuf/bazel/upb_c_proto_library.bzl
[llbuild]                               	thirdparty/protobuf/bazel/upb_minitable_proto_library.bzl
[llbuild]                               	thirdparty/protobuf/bazel/upb_proto_library.bzl
[llbuild]                               	thirdparty/protobuf/bazel/upb_proto_reflection_library.bzl
[llbuild]                               	thirdparty/protobuf/benchmarks/BUILD
[llbuild]                               	thirdparty/protobuf/benchmarks/BUILD.googleapis
[llbuild]                               	thirdparty/protobuf/benchmarks/benchmark.cc
[llbuild]                               	thirdparty/protobuf/benchmarks/build_defs.bzl
[llbuild]                               	thirdparty/protobuf/benchmarks/compare.py
[llbuild]                               	thirdparty/protobuf/benchmarks/descriptor.proto
[llbuild]                               	thirdparty/protobuf/benchmarks
[llbuild]                               Aborting
[llbuild]                               error: could not detach HEAD
Error on repo "/Users/rick/Developer/swift-project/llbuild": Traceback (most recent call last):
  File "/Users/rick/Developer/swift-project/swift/utils/update_checkout/update_checkout/update_checkout.py", line 273, in update_single_repository
    shell.run(["git", "rebase", "FETCH_HEAD"],
  File "/Users/rick/Developer/swift-project/swift/utils/swift_build_support/swift_build_support/shell.py", line 257, in run
    raise eout
Exception: ['git', 'rebase', 'FETCH_HEAD']
...
======UPDATE FAILURES======
/Users/rick/Developer/swift-project/llbuild failed (ret=1): ['git', 'rebase', 'FETCH_HEAD']
b'error: The following untracked working tree files would be overwritten by checkout:\n\tthirdparty/protobuf/.bazelignore\n\tthirdparty/protobuf/.bazelrc\n\tthirdparty/protobuf/.bcr/README.md\n\tthirdparty/protobuf/.bcr/metadata.template.json\n\tthirdparty/protobuf/.bcr/presubmit.yml\n\tthirdparty/protobuf/.bcr/source.template.json\n\tthirdparty/protobuf/.clang-format\n\tthirdparty/protobuf/.github/BUILD.bazel\n\tthirdparty/protobuf/.github/CODEOWNERS\n\tthirdparty/protobuf/.github/ISSUE_TEMPLATE/bug_report.md\n\tthirdparty/protobuf/.github/ISSUE_TEMPLATE/feature_request.md\n\tthirdparty/protobuf/.github/dependabot.yml\n\tthirdparty/protobuf/.github/workflows/README.md\n\tthirdparty/protobuf/.github/workflows/clear_caches.yml\n\tthirdparty/protobuf/.github/workflows/forked_pr_workflow_check.yml\n\tthirdparty/protobuf/.github/workflows/janitor.yml\n\tthirdparty/protobuf/.github/workflows/scorecard.yml\n\tthirdparty/protobuf/.github/workflows/staleness_check.yml\n\tthirdparty/protobuf/.github/workflows/staleness_refresh.yml\n\tthirdparty/protobuf/.github/workflows/test_bazel.yml\n\tthirdparty/protobuf/.github/workflows/test_cpp.yml\n\tthirdparty/protobuf/.github/workflows/test_csharp.yml\n\tthirdparty/protobuf/.github/workflows/test_java.yml\n\tthirdparty/protobuf/.github/workflows/test_objectivec.yml\n\tthirdparty/protobuf/.github/workflows/test_php.yml\n\tthirdparty/protobuf/.github/workflows/test_php_ext.yml\n\tthirdparty/protobuf/.github/workflows/test_python.yml\n\tthirdparty/protobuf/.github/workflows/test_ruby.yml\n\tthirdparty/protobuf/.github/workflows/test_runner.yml\n\tthirdparty/protobuf/.github/workflows/test_rust.yml\n\tthirdparty/protobuf/.github/workflows/test_upb.yml\n\tthirdparty/protobuf/.github/workflows/update_php_repo.yml\n\tthirdparty/protobuf/.gitignore\n\tthirdparty/protobuf/.gitmodules\n\tthirdparty/protobuf/.readthedocs.yml\n\tthirdparty/protobuf/BUILD.bazel\n\tthirdparty/protobuf/CMakeLists.txt\n\tthirdparty/protobuf/CODE_OF_CONDUCT.md\n\tthirdparty/protobuf/CONTRIBUTING.md\n\tthirdparty/protobuf/CONTRIBUTORS.txt\n\tthirdparty/protobuf/Cargo.bazel.lock\n\tthirdparty/protobuf/Cargo.lock\n\tthirdparty/protobuf/LICENSE\n\tthirdparty/protobuf/MODULE.bazel\n\tthirdparty/protobuf/PrivacyInfo.xcprivacy\n\tthirdparty/protobuf/Protobuf-C++.podspec\n\tthirdparty/protobuf/Protobuf.podspec\n\tthirdparty/protobuf/README.md\n\tthirdparty/protobuf/SECURITY.md\n\tthirdparty/protobuf/WORKSPACE\n\tthirdparty/protobuf/appveyor.bat\n\tthirdparty/protobuf/appveyor.yml\n\tthirdparty/protobuf/bazel/BUILD.bazel\n\tthirdparty/protobuf/bazel/cc_proto_library.bzl\n\tthirdparty/protobuf/bazel/common/BUILD.bazel\n\tthirdparty/protobuf/bazel/common/proto_common.bzl\n\tthirdparty/protobuf/bazel/common/proto_info.bzl\n\tthirdparty/protobuf/bazel/common/proto_lang_toolchain_info.bzl\n\tthirdparty/protobuf/bazel/java_lite_proto_library.bzl\n\tthirdparty/protobuf/bazel/java_proto_library.bzl\n\tthirdparty/protobuf/bazel/private/BUILD.bazel\n\tthirdparty/protobuf/bazel/private/native.bzl\n\tthirdparty/protobuf/bazel/private/proto_toolchain_rule.bzl\n\tthirdparty/protobuf/bazel/private/upb_proto_library_internal/aspect.bzl\n\tthirdparty/protobuf/bazel/private/upb_proto_library_internal/cc_library_func.bzl\n\tthirdparty/protobuf/bazel/private/upb_proto_library_internal/copts.bzl\n\tthirdparty/protobuf/bazel/private/upb_proto_library_internal/rule.bzl\n\tthirdparty/protobuf/bazel/proto_library.bzl\n\tthirdparty/protobuf/bazel/py_proto_library.bzl\n\tthirdparty/protobuf/bazel/system_python.bzl\n\tthirdparty/protobuf/bazel/toolchains/BUILD.bazel\n\tthirdparty/protobuf/bazel/toolchains/proto_lang_toolchain.bzl\n\tthirdparty/protobuf/bazel/toolchains/proto_toolchain.bzl\n\tthirdparty/protobuf/bazel/upb_c_proto_library.bzl\n\tthirdparty/protobuf/bazel/upb_minitable_proto_library.bzl\n\tthirdparty/protobuf/bazel/upb_proto_library.bzl\n\tthirdparty/protobuf/bazel/upb_proto_reflection_library.bzl\n\tthirdparty/protobuf/benchmarks/BUILD\n\tthirdparty/protobuf/benchmarks/BUILD.googleapis\n\tthirdparty/protobuf/benchmarks/benchmark.cc\n\tthirdparty/protobuf/benchmarks/build_defs.bzl\n\tthirdparty/protobuf/benchmarks/compare.py\n\tthirdparty/protobuf/benchmarks/descriptor.proto\n\tthirdparty/protobuf/benchmarks\nAborting\nerror: could not detach HEAD\n'
update-checkout failed, fix errors and try again
```

### Expected behavior

no failure

### Environment

swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx15.0

**Comment by vanvoorden** [comment]
https://gist.github.com/vanvoorden/72bda9b91d1baf1fa998e7f6fba69c4f

Here is the complete console output from `utils/update-checkout`.

**Comment by vanvoorden** [comment]
@allevato would you know if anything landed recently in the `protobuf` repo that might lead to these errors?

**Comment by allevato** [comment]
Not that I'm aware of.

It looks like there was this commit in `swift-llbuild` ~a week ago that removed the submodule in favor or just vendoring it directly. Maybe that's related? https://github.com/swiftlang/swift-llbuild/commit/3d685733aa676b63a5f5e289414b19c66fdc1a1a

**Comment by AnthonyLatsis** [comment]
Have you tried deleting llbuild and retrying?

**Comment by vanvoorden** [comment]
> Maybe that's related? [swiftlang/swift-llbuild@3d68573](https://github.com/swiftlang/swift-llbuild/commit/3d685733aa676b63a5f5e289414b19c66fdc1a1a)

Ahh… interesting! So it's possible my `swift-project` directory is in some funky state where my `update-checkout` script was updated but that script might not have the ability to fail gracefully when switching over to the new way of doing things?

**Comment by vanvoorden** [comment]
> Have you tried deleting llbuild and retrying?

Ahh… that works! A clean clone also works for me. I'm unblocked on this. Thanks!

**Comment by vanvoorden** [comment]
I'm unblocked on this. We can close. Thanks!
